### ISSUE TITLE
Solicito permissão para matar

### ISSUE THREAD

**Issue by flaviomicheletti** [ericdouglas/books#1]
Oi Eric!

Este seu repositório se parece muito com um [repositório](https://github.com/flaviomicheletti/code-books) meu. 

Gosto dessa idéia de juntar código de livros!

Gostaria de fazer um fork e contribuir de alguma forma, assim eu aproveito para atualizar (e depois matar) o meu repo.

Obs: não vou arrastar todos os códigos que eu possuo, vou passando aos poucos.

Can I?

**Comment by ericdouglas** [comment]
Beleza @flaviomicheletti ?!

Cara, a intenção deste meu repositório é de deixar os códigos de livros que li, para controle pessoal mesmo, como você pode ver através da lista de [commits](https://github.com/ericdouglas/books/commits/master).

Não exclua seu repo não! 

O que podemos fazer é pensar em uma metodologia de leitura/prática dos códigos dos livros, mostrando como fazemos também com essa parte dos commits, e temos a opção de abrir um novo branch para cada livro também.

Assim, após fecharmos essa metodologia, sintetizamos isso no README e podemos fazer a divulgação, ai a pessoa pode fazer o *fork* do nosso repositório, mas não é necessário o envio do pull request, pois ai ela aproveita mesmo a ideia, e segue em paralelo a partir desta.

O que acha?

**Comment by flaviomicheletti** [comment]
Acho que vai dar um puta trampo (rssss), sorry!

Mas sua idéia é genial! Vendo os commits, percebi que você está inserindo os código aos poucos e com modificações suas, está ficando muito bom (já vi que beberei destas águas).

A idéia do meu repo era apenas centralizar os códigos de livros para facilitar a busca dos mesmos.

abs.

**Comment by ericdouglas** [comment]
As modificações que insiro são os refactors do livro mesmo @flaviomicheletti . Mas dessa forma é como se tivesse fazendo um lembrete dos passos para se criar funcionalidade X.

Vou fazer um esboço em breve do README e te aviso aqui! :smile:
